// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: crawl.sql

package sqlc

import (
	"context"
	"time"
)

const insertCrawl = `-- name: InsertCrawl :exec
insert into crawls (crawl_id, feed_id, status, message, crawled_at)
values ($1, $2, $3, $4, $5)
`

type InsertCrawlParams struct {
	CrawlID   string
	FeedID    string
	Status    CrawlStatus
	Message   *string
	CrawledAt time.Time
}

func (q *Queries) InsertCrawl(ctx context.Context, arg InsertCrawlParams) error {
	_, err := q.db.Exec(ctx, insertCrawl,
		arg.CrawlID,
		arg.FeedID,
		arg.Status,
		arg.Message,
		arg.CrawledAt,
	)
	return err
}
