// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed.sql

package sqlc

import (
	"context"
	"time"
)

const insertFeed = `-- name: InsertFeed :exec
insert into feeds (feed_id, url, title, description, registered_at)
values ($1, $2, $3, $4, $5)
`

type InsertFeedParams struct {
	FeedID       string
	Url          string
	Title        string
	Description  *string
	RegisteredAt time.Time
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) error {
	_, err := q.db.Exec(ctx, insertFeed,
		arg.FeedID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.RegisteredAt,
	)
	return err
}

const selectFeed = `-- name: SelectFeed :one
select feed_id, url, title, description, registered_at, created_at from feeds where feed_id = $1
`

func (q *Queries) SelectFeed(ctx context.Context, feedID string) (Feed, error) {
	row := q.db.QueryRow(ctx, selectFeed, feedID)
	var i Feed
	err := row.Scan(
		&i.FeedID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.RegisteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectFeedsOrderByRegisteredAtAsc = `-- name: SelectFeedsOrderByRegisteredAtAsc :many
select feed_id, url, title, description, registered_at, created_at from feeds order by registered_at asc
`

func (q *Queries) SelectFeedsOrderByRegisteredAtAsc(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, selectFeedsOrderByRegisteredAtAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.FeedID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.RegisteredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
