// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package sqlc

import (
	"context"
	"time"
)

const insertPost = `-- name: InsertPost :exec
insert into posts (post_id, feed_id, crawl_id, title, author, url, summary_original, posted_at)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPostParams struct {
	PostID          string
	FeedID          string
	CrawlID         string
	Title           string
	Author          *string
	Url             string
	SummaryOriginal *string
	PostedAt        time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.db.Exec(ctx, insertPost,
		arg.PostID,
		arg.FeedID,
		arg.CrawlID,
		arg.Title,
		arg.Author,
		arg.Url,
		arg.SummaryOriginal,
		arg.PostedAt,
	)
	return err
}

const selectPostByURL = `-- name: SelectPostByURL :one
select post_id, feed_id, crawl_id, title, author, url, summary_original, posted_at, created_at from posts where url = $1
`

func (q *Queries) SelectPostByURL(ctx context.Context, url string) (Post, error) {
	row := q.db.QueryRow(ctx, selectPostByURL, url)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.FeedID,
		&i.CrawlID,
		&i.Title,
		&i.Author,
		&i.Url,
		&i.SummaryOriginal,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}
