/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FavoriteImport } from './routes/favorite'
import { Route as IndexImport } from './routes/index'
import { Route as FeedsFeedIdImport } from './routes/feeds/$feedId'

// Create/Update Routes

const FavoriteRoute = FavoriteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FeedsFeedIdRoute = FeedsFeedIdImport.update({
  id: '/feeds/$feedId',
  path: '/feeds/$feedId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteImport
      parentRoute: typeof rootRoute
    }
    '/feeds/$feedId': {
      id: '/feeds/$feedId'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof FeedsFeedIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorite' | '/feeds/$feedId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorite' | '/feeds/$feedId'
  id: '__root__' | '/' | '/favorite' | '/feeds/$feedId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoriteRoute: typeof FavoriteRoute
  FeedsFeedIdRoute: typeof FeedsFeedIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoriteRoute: FavoriteRoute,
  FeedsFeedIdRoute: FeedsFeedIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorite",
        "/feeds/$feedId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favorite": {
      "filePath": "favorite.tsx"
    },
    "/feeds/$feedId": {
      "filePath": "feeds/$feedId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
