name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Format Check
        working-directory: infra
        run: terraform fmt -check -recursive
